version: '3.8'

services:
  sonarr-autoimport:
    image: ghcr.io/YOUR_USERNAME/sonarr-autoimport-go:latest
    container_name: sonarr-autoimport-go
    environment:
      - TZ=Europe/Berlin
      - SONARR_URL=http://sonarr:8989
      - SONARR_API_KEY=your_api_key_here
      - SCAN_INTERVAL=300
      - DRY_RUN=false
      - VERBOSE=true
      - DAEMON_MODE=true
    volumes:
      - ./config:/config
      - /path/to/imports:/media
      - /path/to/downloads:/downloads
    restart: unless-stopped
    networks:
      - media_network
    # No ports exposed - this is a background service
    depends_on:
      - sonarr

  # Example Sonarr service (if not already defined elsewhere)
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./sonarr-config:/config
      - /path/to/tv:/tv
      - /path/to/downloads:/downloads
    restart: unless-stopped
    networks:
      - media_network
      - caddy_network
    # Sonarr needs to be accessible via Caddy
    expose:
      - "8989"

networks:
  # Internal network for media services communication
  media_network:
    driver: bridge
    internal: false  # Allows internet access for API calls
    
  # Network shared with Caddy for reverse proxy
  caddy_network:
    external: true  # This should be created externally and shared with Caddy
